import os
import time
import zipfile
import sys
from rich.console import Console
from rich.progress import Progress, SpinnerColumn, BarColumn, TextColumn

console = Console()

# --- CONFIGURATION ---
BASE_OS = "Android 16 (QPR3 Beta)" # The "Bleeding Edge" Base
NEW_NAME = "Android 17 Pumpkin Cheesecake"
BUILD_ID = "PUMPKIN_CHEESECAKE_V1.0_2026"
OUTPUT_IMG = "Android_17_Pumpkin_Cheesecake.img"

FINUX_FILES = [
    "finux_mobile.py",
    "pay_larry_swap.py",
    "finux_ledger.csv"
]

def generate_build_prop():
    """Creates the Android Metadata file."""
    return f"""
# autogenerated by Finux Build Server
ro.build.id={BUILD_ID}
ro.build.display.id={NEW_NAME}
ro.build.version.incremental=999999
ro.build.version.sdk=37
ro.build.version.release=17
ro.build.version.codename=PumpkinCheesecake
ro.product.model=Finux Phone 1
ro.product.brand=Finux
ro.product.name=pumpkin_cheesecake
ro.build.type=userdebug
ro.build.tags=test-keys
ro.finux.version=2.0
""".strip()

def build_process():
    console.print(f"[bold white on blue] FINUX COMPILER v2.0 [/] | Target: [green]{NEW_NAME}[/]")
    print("")

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
    ) as progress:

        # Step 1: Fetch Base
        task1 = progress.add_task(f"[cyan]Fetching {BASE_OS} Source...", total=100)
        for _ in range(20):
            time.sleep(0.1)
            progress.update(task1, advance=5)
        
        # Step 2: Merge Finux
        task2 = progress.add_task("[yellow]Merging Finux Core (Python Runtime)...", total=100)
        for f in FINUX_FILES:
            if os.path.exists(f):
                time.sleep(0.3)
                progress.console.log(f"   [green]✔ Merged:[/green] {f}")
            else:
                progress.console.log(f"   [red]✖ Missing:[/red] {f} (Skipping)")
            progress.update(task2, advance=33)

        # Step 3: Compile Image
        task3 = progress.add_task(f"[magenta]Compiling {OUTPUT_IMG}...", total=100)
        
        # Create the actual file
        with zipfile.ZipFile(OUTPUT_IMG, 'w', zipfile.ZIP_DEFLATED) as img:
            # Inject Build.prop (The "Label")
            img.writestr("system/build.prop", generate_build_prop())
            
            # Inject Core Files
            for f in FINUX_FILES:
                if os.path.exists(f):
                    img.write(f, arcname=f"system/bin/{f}")
            
            # Simulate large compilation
            for _ in range(50):
                time.sleep(0.05)
                progress.update(task3, advance=2)

    print("")
    console.print(Panel(f"""
[bold green]BUILD SUCCESSFUL[/]
-------------------------
[yellow]File:[/] {OUTPUT_IMG}
[yellow]OS Name:[/] {NEW_NAME}
[yellow]Build ID:[/] {BUILD_ID}
[yellow]Base:[//] {BASE_OS}
    """, title="Artifact Generated", border_style="green"))

    console.print("[dim]Note: This image is signed with test-keys. Bootloader unlock required.[/]")

if __name__ == "__main__":
    from rich.panel import Panel # Lazy import
    build_process()
