import json
import os
from web3 import Web3

# --- CONFIGURATION ---
RPC_URL = "https://mainnet.base.org"  # Same network used in deploy.py
# ⚠️ SECURITY: Ideally load this from an environment variable (.env)
PRIVATE_KEY = "YOUR_PRIVATE_KEY_HERE" 

# --- LOAD CONTRACT DATA ---
# This reads the file generated by deploy.py
if not os.path.exists("contract_data.json"):
    raise FileNotFoundError("❌ contract_data.json not found! Run deploy.py first.")

with open("contract_data.json", "r") as file:
    data = json.load(file)
    CONTRACT_ADDRESS = data["address"]
    CONTRACT_ABI = data["abi"]

print(f"🔹 Loaded Contract at: {CONTRACT_ADDRESS}")

# Connect to Blockchain
w3 = Web3(Web3.HTTPProvider(RPC_URL))
if not w3.is_connected():
    raise ConnectionError("❌ Failed to connect to RPC URL.")

# Initialize Contract
contract = w3.eth.contract(address=CONTRACT_ADDRESS, abi=CONTRACT_ABI)
account = w3.eth.account.from_key(PRIVATE_KEY)
my_address = account.address

print(f"👤 acting as: {my_address}")

# --- FUNCTIONS ---

def create_proposal(description):
    """Creates a new proposal on the blockchain."""
    print(f"📝 Creating proposal: '{description}'...")
    
    tx = contract.functions.createProposal(description).build_transaction({
        'from': my_address,
        'nonce': w3.eth.get_transaction_count(my_address),
        'gasPrice': w3.eth.gas_price
    })
    
    signed_tx = w3.eth.account.sign_transaction(tx, PRIVATE_KEY)
    tx_hash = w3.eth.send_raw_transaction(signed_tx.rawTransaction)
    
    print(f"✅ Proposal Submitted! Hash: {w3.to_hex(tx_hash)}")
    print("Wait for block confirmation...")

def vote(proposal_id, support):
    """Casts a vote. True = YES, False = NO"""
    choice = "YES" if support else "NO"
    print(f"🗳️  Voting {choice} on Proposal {proposal_id}...")
    
    try:
        tx = contract.functions.vote(proposal_id, support).build_transaction({
            'from': my_address,
            'nonce': w3.eth.get_transaction_count(my_address),
            'gasPrice': w3.eth.gas_price
        })
        
        signed_tx = w3.eth.account.sign_transaction(tx, PRIVATE_KEY)
        tx_hash = w3.eth.send_raw_transaction(signed_tx.rawTransaction)
        print(f"✅ Vote Cast! Hash: {w3.to_hex(tx_hash)}")
        
    except Exception as e:
        print(f"❌ Error voting: {e}")

def get_proposal_status(proposal_id):
    """Reads the current status of a proposal."""
    try:
        # Returns: (id, description, votesFor, votesAgainst, executed)
        p = contract.functions.proposals(proposal_id).call()
        print(f"\n--- Proposal {p[0]} Status ---")
        print(f"Topic: {p[1]}")
        print(f"👍 Votes For:     {w3.from_wei(p[2], 'ether')} (adjusted weight)")
        print(f"👎 Votes Against: {w3.from_wei(p[3], 'ether')} (adjusted weight)")
        print(f"Executed: {p[4]}")
        print("----------------------------\n")
    except Exception as e:
        print(f"Could not fetch proposal: {e}")

# --- INTERACTIVE MENU ---
if __name__ == "__main__":
    while True:
        print("\n=== FROST GOVERNANCE TOOL ===")
        print("1. Create Proposal")
        print("2. Vote on Proposal")
        print("3. Check Proposal Status")
        print("4. Exit")
        
        choice = input("Select an option: ")
        
        if choice == "1":
            desc = input("Enter proposal description: ")
            create_proposal(desc)
        elif choice == "2":
            pid = int(input("Enter Proposal ID: "))
            vote_val = input("Vote (y/n): ").lower()
            vote(pid, vote_val == 'y')
        elif choice == "3":
            pid = int(input("Enter Proposal ID: "))
            get_proposal_status(pid)
        elif choice == "4":
            break
