import webbrowser
import requests

class FrostPay:
    def __init__(self):
        self.api_url = "https://api.frost-protocol.io/create-checkout" 
        # (This endpoint would call Stripe.checkout.sessions.create on your backend)

    def buy_frostcoin(self, wallet_address, amount_usd):
        """
        Generates a Google Pay Checkout Link
        """
        print(f"[\u26A1 FrostPay] Initiating GPay Request for ${amount_usd}...")
        
        # Simulate getting a session URL from your backend
        # In production, this requests your Flask server to build the Stripe Session
        checkout_url = self._get_stripe_url(wallet_address, amount_usd)
        
        if checkout_url:
            print(f"[\u2197 OPENING] Launching Google Pay Secure Sheet...")
            # This opens the default browser on Finux/Android
            webbrowser.open(checkout_url)
            return "Check your browser to complete payment."
        else:
            return "Error creating payment session."

    def _get_stripe_url(self, wallet, amount):
        # Mocking the backend response for the 'checkout' link
        # This link would actually be generated by stripe.checkout.sessions.create
        # with metadata={'wallet_address': wallet}
        
        # Example of what the backend returns:
        return "https://checkout.stripe.com/pay/cs_test_a1b2c3..." 

# Integration into your existing FUI
if __name__ == "__main__":
    # Test Run
    pay = FrostPay()
    my_wallet = "0xJacobFrostWalletAddress123"
    print(pay.buy_frostcoin(my_wallet, 50)) # Buy $50 worth
# Virgo_Core_v2.py (PATCHED)
import os
import requests
from openai import OpenAI
from google import genai

class VirgoCore:
    def __init__(self):
        self.offline_mode = False
        
        # Guard: Check Sora Key
        if not os.getenv("OPENAI_API_KEY"):
            print("⚠️  Warning: OPENAI_API_KEY missing. Sora disabled.")
            self.sora_client = None
        else:
            self.sora_client = OpenAI()

        # Guard: Check Veo Key
        if not os.getenv("GEMINI_API_KEY"):
            print("⚠️  Warning: GEMINI_API_KEY missing. Veo disabled.")
            self.veo_client = None
        else:
            # Initialize with error catching
            try:
                self.veo_client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
            except Exception as e:
                print(f"❌ Veo Init Failed: {e}")
                self.veo_client = None

    def safe_generate(self, prompt, engine="veo"):
        if self.offline_mode:
            return ">> System Offline. Check logs."
            
        if engine == "veo" and not self.veo_client:
            return ">> Error: Veo API Key missing."
            
        # ... (Rest of logic proceeds safely) ...
        return f">> [MOCK] Generated video for: {prompt}"
